#!/bin/sh  
#/etc/init.d/domotic_pi

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
        start)
        exec forever --sourceDir=/home/pi/Domotic/Room server.js
        ;;
        stop)
        exec forever stop --sourceDir=/home/pi/Domotic/Room server.js
        ;;
        *)
        echo "usage: /etc/init.d/domotic_pi {start|stop}"
        exit 1
        ;;
esac

exit 0
